name: Flutter Web
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Decode base64 secrets
        run: echo $SECRETS_FILE_CONTENT | base64 -di > lib/secrets.dart
        env:
          SECRETS_FILE_CONTENT: ${{ secrets.SECRETS_FILE_CONTENT }}
      - run: flutter config --enable-web
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build web --release --web-renderer html
      - run: |
          cd build/web
          git init
          # type configurations: your user.email and user.name followed lines 
          git config --global user.email jason100122@gmail.com
          git config --global user.name douobb
          git status
          # change this remote url for examle your remote url is https://github.com/onatcipli/flutter_web.git then the following:
          git remote add origin https://${{secrets.commit_secret}}@github.com/douobb/pc_case_filter.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
